### ISSUE TITLE
Curso Processamento Neural de Linguagem Natural em Português I  (Coursera)

### ISSUE THREAD

**Issue by renatosampaio81** [alan-barzilay/NLPortugues#11]
Estou enfrentando um problema de verificação na entrega da semana 04 no curso "Processamento Neural de Linguagem Natural em Português I" no Coursera. 

Os códigos sgd.py e word2vec.py geram resultados corretos quando executados localmente, no entanto, ao realizar a entrega, ocorre erro. 

No fórum outros colegas também estão enfrentando o mesmo problema. Gostaria gentilmente que verificasse essa situação quando possível.

Agradeço pela atenção.

**Comment by alan-barzilay** [comment]
Ola, obrigado por abrir o issue. O coursera deixa a desejar entao muitas vezes nem ficamos sabendo de posts novos no forum ou problemas que os alunos podem estar enfrentando.

Poderia me apontar para a thread do forum sobre isso? Para mim aparece que nao existem postagens para a semana 4.

Alem disso, poderia me fornecer uma copia do seu codigo para que eu possa testar e averiguar a origem do problema?

**Comment by renatosampaio81** [comment]
Sr. Barzilay, boa tarde. A thread que colegas estão comentando a dificuldade relatada é o: https://www.coursera.org/learn/processamento-neural-linguagem-natural-em-portugues-i/discussions/forums/C2_bY5L7Ee2UihJKQD691w/threads/koQ4ZWJIEe6jZRJQzEcqdQ


Em um compilado dos erros reportados pelo verificador, no coursera:

- word2vec.py : "Your code returned this error: No module named 'utils" - É como se o verificador não tivesse acesso ao módulo utils ao rodar o word2vec.py

- sgd.py : "Your code returned this error: module 'submission' has no attribute 'main'" - Para corrigir o problema tentei adicionar uma função main que contém o código que desejo executar quando o script é executado, adicionando uma função main que chama a função sanity_check, e o bloco if __name__ == "__main__": agora chama a função main. Ao submeter ao verificador aparentemente o erro é corrigido mas informa que meu código está incorreto.

- vetores_de_palavras.png: "Your file may not have the right extension" - Utilizei editores de imagens distintos para fornecer uma nova png, mas o verificador mantém o erro.

Por fim, gostaria de expressar meus sinceros agradecimentos pela qualidade do curso, que tem me proporcionado valiosos insights na área. A metodologia de ensino, aliada à expertise dos professores, tem contribuído significativamente para o meu desenvolvimento profissional. Agradeço pela oportunidade de aprender com os melhores e por todo o suporte oferecido. Muito obrigado.

obs. Este fórum não suporta envio de arquivos com extensão py, então salvei os arquivos como txt
[word2vec.txt](https://github.com/alan-barzilay/NLPortugues/files/13467786/word2vec.txt)
[sgd.txt](https://github.com/alan-barzilay/NLPortugues/files/13467787/sgd.txt)

**Comment by alan-barzilay** [comment]
<img width="603" alt="image" src="https://github.com/alan-barzilay/NLPortugues/assets/28787373/20f8388a-9a22-4a93-8fb8-81946387aad4">
coursera eh tao ruim q nem me permite ver esse topico, vou testar uma gambiarra pra ver se consigo acesso. Mas se nem acesso eu tenho direito (como instrutor ainda por cima), vc pode imaginar que n recebi nenhuma notificacao sobre as dificuldades q vcs estao encontrando.


Pelos erros q vc relatou, suspeito que algo deu  errado com o docker do autograder, suspeito q o coursera esta usando a imagem errada por algum motivo. Vou investigar melhor e espero retornar com uma solucao o quanto antes.

**Comment by alan-barzilay** [comment]
@renatosampaio81 vc poderia me informar o que esta escrito nessa parte da UI com o retangulo vermelho quando logado na sua conta? Se mostra Release 01 ou  Group 01- teste

<img width="642" alt="image" src="https://github.com/alan-barzilay/NLPortugues/assets/28787373/1eb076b7-d92c-4f87-94ef-72ac0f6ca166">

**Comment by renatosampaio81** [comment]
Olá @alan-barzilay, boa tarde. Na minha visão não consta essa barra, observe o anexo. Esta é visão via navegador no desktop, mas tentei via app android mas o resultado é semelhante. Acredito que essa visão seja apenas para o corpo docente do curso.
![Capturar](https://github.com/alan-barzilay/NLPortugues/assets/78216917/d8435a0a-0ce5-4481-89a8-0432039fdf12)

**Comment by alan-barzilay** [comment]
Tudo bom @renatosampaio81? Desculpe a demora em retornar para você e  espero q tenha passado bem o ano novo, acredito que descobri o que havia de errado e consegui consertar tudo. Haviam umas pequenas inconsistências entre os arquivos de exemplo presentes nesse repositorio e o que o nosso autograder esperava. 
Normalmente isso nao seria um problema muito grande e consertariamos rapido, a questo eh que o cursourera eh muito difcil de se trabalhar com e  nos gerou uma serie de problemas que tivemos de resolver antes de atacar isso.

Por gentileza você poderia testar se a sua submisso funciona agora? O grader deve funcionar normalmente, você apenas terá que fazer pequenas modificações muito simples e rápidas nos arquivos sgd.py e wordvec.py (remover a importacao de utils, adicionar a funcao main e substituir o string que eh impresso a cada 100 iteracoes no arquivo sgd).

Vc pode se guiar pelos novos templates se achar mais fácil segue aqui o commit com as alterações realizadas:
https://github.com/alan-barzilay/NLPortugues/commit/666dc3199e1c2ddf59c8fb7b4375d25d812f49c7
https://github.com/alan-barzilay/NLPortugues/commit/a01c183853af2b82d5e969451079569211292e22


Acredito que tudo esta em ordem agora, mas gostaria de ter certeza que os alunos conseguem realmente realizar a entrega antes de marcar o issue como resolvido, tivemos mais de um problema onde o coursera nos mostrou uma coisa enquanto mostrava outra (normalmente desatualizada e quebrada) para os alunos.

**Comment by alan-barzilay** [comment]
ah, a submissao da semana 6 tb deve estar consertada, caso vc tenha chegado a terminar o curso

**Comment by renatosampaio81** [comment]
Prezado @alan-barzilay, agradeço e retribuo os votos de bom ano.. Entendo você, as plataformas para EAD vem se aperfeiçoando bastante ao longo do tempo mas ainda tem muito a melhorar. Agradeço pelo esforço na busca de tornar o curso acessível e por todo conhecimento que você compartilha conosco.

Como o período de acesso da minha turma já havia encerrado, precisei me inscrever em uma nova turma, que inicia em 28 de fevereiro. A partir desta data vou poder submeter os exercícios para revisão do autograder e retorno com um feedback pra você. 

Caso os colegas que vem acompanhando esse tópico, e que estejam em turma aberta, já quiserem compartilhar sua experiência, com certeza será de grande valia pra todos nós.

**Comment by alan-barzilay** [comment]
> Agradeço pelo esforço na busca de tornar o curso acessível e por todo conhecimento que você compartilha conosco.

❤️<3

> Como o período de acesso da minha turma já havia encerrado, precisei me inscrever em uma nova turma, que inicia em 28 de fevereiro. A partir desta data vou poder submeter os exercícios para revisão do autograder e retorno com um feedback pra você.

O coursera nao te deixa submeter? q odio haha era para estar configurado de outra forma, se eu descobrir como mudar isso eu retorno aqui mas bastante certeza que eh mais um "bug" deles sobre o qual nao temos poder.

**Comment by voaneves** [comment]
@alan-barzilay Boa tarde!

Tentei submeter novamente, porém o mesmo erro foi mantido:

![image](https://github.com/alan-barzilay/NLPortugues/assets/12961202/b7a3587a-e7bb-4e74-b8c4-1652fe31e3dc)

Como procedo?

**Comment by alan-barzilay** [comment]
@voaneves boa tarde, estou esperando o coursera colocar no ar a versao nova do curso. Infelizmente nao consigo fazer nada alem de esperar eles retornarem

**Comment by voaneves** [comment]
@alan-barzilay me equivoquei no último! Postei sem as modificações que você fez no commit https://github.com/alan-barzilay/NLPortugues/commit/a01c183853af2b82d5e969451079569211292e22. Agora, porém, aparentemente o que estou postando está errado:

<img width="624" alt="image" src="https://github.com/alan-barzilay/NLPortugues/assets/12961202/1d376abc-857c-4669-aa70-ffaeff40784c">

Você sabe se é possível debugar? Pra ver qual linha deu problema, ou pelo onde eu errei. Obrigado!

**Comment by alan-barzilay** [comment]
o autograder esta errado, vc pode estar correto. Estou aguardando o coursera fazer sua parte para consertar isso

**Comment by voaneves** [comment]
> o autograder esta errado, vc pode estar correto. Estou aguardando o coursera fazer sua parte para consertar isso

Poxa, perfeito então! Quando eu entrei no curso, fui alertado que a versão já tinha avançado e pensei que já pudesse. Vou tentar postar a week 6 hoje mais tarde. 

Obrigado!

**Comment by alan-barzilay** [comment]
@renatosampaio81 acredito que agora vc deve conseguir realizar a submissao (passou a data q vc comentou mas tb mudei umas configuracoes do coursera para acabar com essa espera). Poderia me dizer se conseguiu submeter apos fazer as duas mudancas q eu comentei? (https://github.com/alan-barzilay/NLPortugues/commit/666dc3199e1c2ddf59c8fb7b4375d25d812f49c7 , https://github.com/alan-barzilay/NLPortugues/commit/a01c183853af2b82d5e969451079569211292e22)

**Comment by alan-barzilay** [comment]
@voaneves vc poderia me enviar seu vetores_de_palavras.png? e seu sgd.py passa todos os testes? vc realizou a mudanca no formato do output descrita aqui? o output deve seguir a seguinte estrutura:


```
Rodandos testes...
Iteração No.100, Loss: 0.004578
Iteração No.200, Loss: 0.004353
Iteração No.300, Loss: 0.004136
Iteração No.400, Loss: 0.003929
Iteração No.500, Loss: 0.003733
Iteração No.600, Loss: 0.003546
Iteração No.700, Loss: 0.003369
Iteração No.800, Loss: 0.003200
Iteração No.900, Loss: 0.003040
Iteração No.1000, Loss: 0.002888
teste 1: 8.414836786079764e-10
Iteração No.100, Loss: 0.000000
Iteração No.200, Loss: 0.000000
Iteração No.300, Loss: 0.000000
Iteração No.400, Loss: 0.000000
Iteração No.500, Loss: 0.000000
Iteração No.600, Loss: 0.000000
Iteração No.700, Loss: 0.000000
Iteração No.800, Loss: 0.000000
Iteração No.900, Loss: 0.000000
Iteração No.1000, Loss: 0.000000
etc
```

**Comment by voaneves** [comment]
@alan-barzilay tinha deixado passar as modificacões no output. Alterei e saiu da seguinte forma:

![image](https://github.com/alan-barzilay/NLPortugues/assets/12961202/a33207f0-651d-443b-aa13-4a8da8221e5f)

Só o vetor de palavras que não bateu.

![vetores_de_palavras](https://github.com/alan-barzilay/NLPortugues/assets/12961202/c18a953e-565c-4b4b-8222-9724cfb63e3a)

Esse é o meu `vetor_de_palavras.png`. O que acha que pode ser? O vetor ficou com algum problema?

Edit: sobre a semana 6, ainda não tentei!!

**Comment by alan-barzilay** [comment]
@voaneves que interessante, a sua imagem esta completamente diferente do esperado haha
![image](https://github.com/alan-barzilay/NLPortugues/assets/28787373/a0fe6bc2-6b41-40c2-9fa4-159eafea4e89)

vc poderia me encaminhar seu word2vec.py e sgd.py? era pra ser algo deterministico, gostaria de entender como isso aconteceu. Talvez tenha q mudar a abordagem da correcao (o embedding ser diferente nao significa que esta errado, mas a principio tomamos medidas no run.py para tornar o resultado sempre o mesmo)

**Comment by renatosampaio81** [comment]
> @renatosampaio81 acredito que agora vc deve conseguir realizar a submissao (passou a data q vc comentou mas tb mudei umas configuracoes do coursera para acabar com essa espera). Poderia me dizer se conseguiu submeter apos fazer as duas mudancas q eu comentei? ([666dc31](https://github.com/alan-barzilay/NLPortugues/commit/666dc3199e1c2ddf59c8fb7b4375d25d812f49c7) , [a01c183](https://github.com/alan-barzilay/NLPortugues/commit/a01c183853af2b82d5e969451079569211292e22))

Prezado @alan-barzilay , boa tarde, tudo bem ?

A exemplo do @voaneves, submeti com sucesso os dois arquivos py mas obtive falha com o png. A diferença apenas é que meu png se assemelha ao que você postou em 29/02. 
![avaliacao](https://github.com/alan-barzilay/NLPortugues/assets/78216917/897ecf8b-06e5-4fb8-acda-8fe4f41bdcf2)
 
Gostaria que eu compartilhasse os três arquivos para que você pudesse visualizar melhor ?

**Comment by alan-barzilay** [comment]
@renatosampaio81, sim por favor! 
Vc tb poderia me dizer qual eh o tamanho da sua imagem png? Quero dizer as dimensoes  em pixels, todos deveriam ter a mesma dimensao default mas pelo jeito isso n esta acontecendo. Talvez eu tenha q editar o run.py pra forcar uma dimensao especifica, nao consigo testar a imagem se ela estiver numa dimensao arbitraria.

**Comment by renatosampaio81** [comment]
@alan-barzilay O tamanho 31,6 kb , as dimensões 640x480. Pode ter sido alguma coisa que alterei sem querer também.

![vetores_de_palavras](https://github.com/alan-barzilay/NLPortugues/assets/78216917/bbb6ec3c-ae5a-452f-ba58-9ec196ecf3c9)
[word2vec.txt](https://github.com/alan-barzilay/NLPortugues/files/14511262/word2vec.txt)
[sgd.txt](https://github.com/alan-barzilay/NLPortugues/files/14511263/sgd.txt)

**Comment by alan-barzilay** [comment]
pelo jeito agora ta resolvido, obtive confirmacao em #16. Vou marcar aqui como resolvido tb

**Comment by voaneves** [comment]
Alan, realmente está corrigido (y)

![image](https://github.com/alan-barzilay/NLPortugues/assets/12961202/d34985d5-120e-4e71-bc99-584d6f4208fc)

Obrigado!
