### ISSUE TITLE
Problemas com o 'vetores_de_palavras.png'

### ISSUE THREAD

**Issue by Manolo789** [alan-barzilay/NLPortugues#16]
Estou enfrentando um problema de verificação na entrega da semana 04 no curso "Processamento Neural de Linguagem Natural em Português I" no Coursera.

Tanto na plataforma quanto localmente os arquivos 'sgd.py' e 'word2vec.py' detêm resultados corretos, no entanto, ao entregar a imagem 'vetores_de_palavras.png' não obtenho qualquer tipo de nota, o contador de notas fica zerado como mostra o anexo.

Se for possível, gostaria que analisassem este problema.
Desde já, grato pela atenção.

PS: Estou incluindo também no anexo os arquivo 'sgd.py', 'word2vec.py' e 'vetores_de_palavras.png' para possível análise. No entanto, como o GitHub não suporta a extensão '.py', a extensão destes arquivos estará como '.txt'.

![Screenshot 2024-03-19 at 16-27-25 Implementando word2vec Coursera](https://github.com/alan-barzilay/NLPortugues/assets/92552607/10201d7f-5f76-4057-b1a7-4f08b9d59a7c) 
![vetores_de_palavras](https://github.com/alan-barzilay/NLPortugues/assets/92552607/b4c52e71-28c0-4669-a345-3eabbb1943b6)
[word2vec.txt](https://github.com/alan-barzilay/NLPortugues/files/14655450/word2vec.txt)
[sgd.txt](https://github.com/alan-barzilay/NLPortugues/files/14655449/sgd.txt)

**Comment by Jonnathanz** [comment]
@Manolo789 conseguiu resolver? Tive o mesmo resultado que o seu aqui.

**Comment by Jonnathanz** [comment]
@alan-barzilay

**Comment by Manolo789** [comment]
Desculpe, eu sem querer apertei o botão de fechar o issue (ainda sou meio novato no github), mas já o reabri. Quanto ao problema, eu ainda não descobri como resolver.

**Comment by Manolo789** [comment]
Eu estava fazendo alguns testes e percebi uma possível causa do erro. Acompanhem meu raciocínio:

 Se no Coursera os arquivos 'sgd.py' e 'word2vec.py' recebem nota máxima, então o algoritmo em si não é o problema, já que passou pelo testes automatizados. Então, onde o problema poderia estar?

 Eu acredito (isso é só uma suposição) que o erro se encontra no arquivo 'd2w.csv' pelo simples fato de que o Coursera mostra que o algoritmo esta certo, logo, o que pode estar errado são os dados para treinamento. Talvez, o arquivo de treinamento do Cousera do teste automatizado esteja desatualizado em relação ao arquivo de treinamento neste repositório.

**Comment by alan-barzilay** [comment]
@Manolo789 @Jonnathanz vcs poderiam tentar submeter novamente? Esse foi um bug meio chato de corrigir, mas ao q tudo indica ele esta resolvido. Por favor me digam se agora vcs conseguem fazer a entrega para eu marcar esse issue como resolvido

**Comment by Manolo789** [comment]
Acabei de submeter a tarefa e o erro foi corrigido. Segue a imagem do Coursera:

![Screenshot 2024-03-23 at 13-00-26 Implementando word2vec Coursera](https://github.com/alan-barzilay/NLPortugues/assets/92552607/2a6c5f15-de88-4294-8090-56d8902b6b93)

**Comment by alan-barzilay** [comment]
Boa! acho q ta tudo resolvido entao, obrigado pela paciencia
